### ISSUE TITLE
Is the PermonFLLOP link in README.md still relevant?

### ISSUE THREAD

**Issue by haplav** [It4innovations/permon#10]
Maybe it should be mentioned as just a part of PermonQP.

**Comment by jkruzik** [comment]
This should be improved at the same time as the update of the web page (cc: @mpecha). We mention in the readme:
> PERMON ... . It also includes domain decomposition methods (FETI and Total FETI) as a specific QP implementation.

I think we should discontinue the use of the FLLOP name altogether and just use the above in the description of PERMON.

**Comment by haplav** [comment]
Sounds good to me. I can try to update the README.
