### ISSUE TITLE
tutorials-jbearing2_3 test issue

### ISSUE THREAD

**Issue by haplav** [It4innovations/permon#19]
1. I get
   ```
   not ok tutorials-jbearing2_3 # Exceeded timeout limit of 60 s
   ```
   so I added
   ```
     timeoutfactor: 2
   ```
2. But then I get
```
not ok diff-tutorials-jbearing2_3 # Error code: 1
#	8,9c8,9
#	<   last QPSSolve CONVERGED due to CONVERGED_ATOL, KSPReason=3, required 2361 iterations
#	<   all 1 QPSSolves from last QPSReset/QPSResetStatistics have required 2361 iterations
#	---
#	>   last QPSSolve CONVERGED due to CONVERGED_ATOL, KSPReason=3, required 2637 iterations
#	>   all 1 QPSSolves from last QPSReset/QPSResetStatistics have required 2637 iterations
#	18c18
#	<         Gradient steps: 678
#	---
#	>         Gradient steps: 780
#	28,30c28,30
#	<             Number of updates: 2352
#	<             Number of rejects: 8
#	<             Number of resets: 688
#	---
#	>             Number of updates: 2635
#	>             Number of rejects: 1
#	>             Number of resets: 785
#	39c39
#	<                 Number of updates: 2352
#	---
#	>                 Number of updates: 2635
#	41c41
#	<                 Number of resets: 696
#	---
#	>                 Number of resets: 786
#	53c53
#	<         Residual in Function/Gradient:=9.99023e-09
#	---
#	>         Residual in Function/Gradient:=9.92755e-09
#	55,56c55,56
#	<         total number of iterations=2361,                                (max: 2000)
#	<         total number of function/gradient evaluations=5109,            (max: 4000)
#	---
#	>         total number of iterations=2637,                                (max: 2000)
#	>         total number of function/gradient evaluations=5159,            (max: 4000)
#	58c58
#	< norm of difference of results from TAO and QP = 7.624551e-07  
#	---
#	> norm of difference of results from TAO and QP = 3.516641e-07  

# -------------
#   Summary    
# -------------
# FAILED diff-tutorials-jbearing2_3
```

I assume this TAO iteration is not stable enough to yield always the same numbers. But what to do with that? A few possibilities here:
1. limit number of iterations
2. remove `-qps_view_convergence` as the results are compared anyway
3. use some filtering
4. use alt files

**Comment by haplav** [comment]
Additionally, I think we should throw an error if the `norm of difference of results from TAO and QP` is greater than some threshold. Currently, the norm of difference is only printed but PETSc test harness ignores floating point numbers.

**Comment by jkruzik** [comment]
Is there an option when specifying tests to not ignore scientific notation / floats? It would be very useful to check KKT conditions which are printed with only a few decimal places in the scientific notation.

I thought the number in scientific notation are not ignored but looking at petscdiff this is clearly not the case. However, if I change a value in ex1_1 for a KKT condition the test passes but when I also change something else the diff outputs:
```
not ok diff-tutorials-ex1_1+a # Error code: 1
#       4c4
#       <     number of expansion steps 28
#       ---
#       >     number of expansion steps 18
#       8c8
#       < r = ||min(lambda_lb,0)|| = 1.87e-07    r/||b|| = 6.17e-01
#       ---
#       > r = ||min(lambda_lb,0)|| = 1.87e-07    r/||b|| = 6.17e-06
```

**Comment by haplav** [comment]
> Is there an option when specifying tests to not ignore scientific notation / floats?

Not at the moment, I'm afraid.

> However, if I change a value in ex1_1 for a KKT condition the test passes but when I also change something else the diff outputs:

Yes, this is a normal behavior. If there are difference _only_ in floating points, it passes. If there is any non-floating difference, then all differences are printed _including_ floating points. It might be questionable but it's definitely a PETSc question rather than a PERMON question.
