### ISSUE TITLE
QPGetInitialVector is missing

### ISSUE THREAD

**Issue by lukaspospisil** [It4innovations/permon#2]
QPSetInitialVector is great, but sometimes user wants to also get this vector (for example to test if the value was stored inside QP or to test if the vector was even provided - is the default value zero or ...?).
Please, provide also QPGetInitialVector(QP, Vec *). Or maybe - the provided x0 is automatically stored in SolutionVector, therefore it could be obtained using QPGetSolutionVector?

**Comment by haplav** [comment]
Yes, the Vec obtained from QPGetSolutionVector is the same object as that set using QPSetInitialVector. This is inspired by TAOSetInitialVector/TAOGetSolutionVector. Thus the vector obtained with QPGetSolutionVector contains the initial guess before QPSSolve, and the solution after QPSSolve. It's the same object in both cases but the values get changed. If you need to keep the initial values, copy them to another vector before QPSSolve. The initial guess is all zeros by default (if QPSetInitialVector is not called). Do you need to have possibility to know whether the initial vector was user-provided?
