### ISSUE TITLE
should QPSMPGP use VecBoundGradientProjection for gradient projection?

### ISSUE THREAD

**Issue by haplav** [It4innovations/permon#39]

**Comment by jkruzik** [comment]
I do not think so. We usually need explicitly free and chopped gradients and if we have these a simple VecAXPY to obtain projected gradient is preferable than repeating the same loop with comparisons. Moreover, gradient splitting in QPC support tolerances which are very useful in floating-point arithmetic.

**Comment by haplav** [comment]
OK
